export const ADD_GROUP = 'ADD_GROUP';
export const REMOVE_GROUP = 'REMOVE_GROUP';
export const RENAME_GROUP = 'RENAME_GROUP';

export const SUBMIT_SURVEY_ANSWERS = 'SUBMIT_SURVEY_ANSWERS';
export const SURVEY_DATA_RETRIEVED = 'SURVEY_DATA_RETRIEVED';
export const SURVEY_OVERVIEW_RETRIEVED = 'SURVEY_OVERVIEW_RETRIEVED';
export const SURVEY_DELETED_SUCCESS = 'SURVEY_DELETED_SUCCESS';
export const LOAD_SURVEY = 'LOAD_SURVEY';
export const SURVEY_RETRIEVED = 'SURVEY_RETRIEVED';
export const LOAD_SURVEY_RESULTS = 'LOAD_SURVEY_RESULTS';
export const SURVEY_RESULTS_DATA_RETRIEVED = 'SURVEY_RESULTS_DATA_RETRIEVED';

export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const USER_SIGNUP = 'USER_SIGNUP';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const SET_USER_VISIBILITY_FILTER = 'SET_USER_VISIBILITY_FILTER';
export const RETRIEVE_USER_DATA_SUCCESS = 'RETRIEVE_USER_DATA_SUCCESS';

export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
export const SHOW_FORGOT_PASSWORD_ERROR = 'SHOW_FORGOT_PASSWORD_ERROR';

export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
